pipeline {

  environment {
    registry = "aksmigrationstudy"
    registryUrl = "aksmigrationstudy.azurecr.io"
    dockerImage = ""
 }

  agent any

  stages {

    stage('Checkout Source') {
      steps {
        git branch: "master",
        url: 'https://github.com/priyabadi/sampleapp.git'
      }
    }

    stage('Build image') {
      steps {
        script {
          dockerImage = docker.build(registry + ":$BUILD_NUMBER", "-f build_image_w_git_parameter/app/Dockerfile .")
        }
      }
    }

    stage('Push Image') {
      steps{
        script {
          docker.withRegistry( 'http://${registryUrl}', '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' ) {
            dockerImage.push()  
            }
          }
        }
      }
  }
}
